### ISSUE TITLE
Parsing ISO date is broken when dayfirst=True (since 2.5.2 release)

### ISSUE THREAD

**Issue by svetlyak40wt** [dateutil/dateutil#241]
Before 2.5.2 release, parse with dayfirst=True, parsed dates like '2015-02-06' as expected 2 – month and 06 – day. This is right, because `-` delimiter is only possible in ISO 8601. According to this list: https://en.wikipedia.org/wiki/Date_format_by_country, format yyyy-dd-mm is not used anywhere.

Seems, pull request https://github.com/dateutil/dateutil/pull/229 broken this behavior.

Can we please fix it, because I need to parse '2015-02-06' as 6 February, but if date was given as 06.02.15 consider first number is a day.

**Comment by pganssle** [comment]
This is fixed in the 2.5.x branch and there will be a 2.5.3 release at some point relatively soon fixing it. Suggested work around is to either use version 2.5.1 (a fix to dayfirst/yearfirst is the only substantive change in 2.5.2) or use the 2.5.x branch.

**Comment by svetlyak40wt** [comment]
Ok, thank you.

BTW, this library is quite useful for [my pet-project](https://allmychanges.com), which is about release notes parsing where dates could have very different format.

**Comment by serge-gaia** [comment]
So this won't be fixed, correct? I'm using 2.6.0 and I still have this problem.

**Comment by pganssle** [comment]
@serge-gaia I don't know what exactly you mean by "won't be fixed". `dayfirst`'s behavior won't be going back to the old behavior, but at some point when there's time I think a more flexible date parsing specification is called for.

**Comment by mcarans** [comment]
For those who need this functionality and find this issue, you can either use higher level functions I've implemented here:
https://github.com/OCHA-DAP/hdx-python-utilities#date-parsing-utilities

Or if you want the same interface as dateutils, then you use hdx.utilities.dateparse.parse which is modified for ambiguous dates to be day first D/M/Y where there are values in front of the year and day last Y/M/D where there are values after the year and for fuzzy_with_tokens, returns datetime, skipped tokens, date tokens.
